# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_dvd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libuser',
            name='age',
        ),
        migrations.AddField(
            model_name='libitem',
            name='num_chkout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libuser',
            name='postalcode',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 5, 18)),
        ),
    ]
