# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0006_auto_20160525_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libitem',
            name='overdue',
        ),
    ]
