# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_remove_libitem_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='libitem',
            name='overdue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
