# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0010_auto_20160614_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='libuser',
            name='photo',
            field=models.ImageField(blank=True, height_field=1080, null=True, upload_to='', width_field=1080),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 22)),
        ),
    ]
