# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0011_auto_20160622_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./libapp/profile_photo'),
        ),
    ]
