# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0013_auto_20160622_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 25)),
        ),
        migrations.AlterField(
            model_name='libuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='/profile_photo'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='num_interested',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='type',
            field=models.CharField(choices=[('Book', 'Book'), ('DVD', 'DVD'), ('Other', 'Other')], default='Other', max_length=6),
        ),
    ]
